#!/usr/bin/env python3
from ccpbsa import *
import argparse

if __name__ == '__main__':
    cliparser = argparse.ArgumentParser(prog='ccpbsa')

#    Positional arguments
    cliparser.add_argument("wildtype", help=".pdb file of the wildtype protein")
    cliparser.add_argument("mutations",
        help="a .txt file with the list of mutations")
    cliparser.add_argument("flags",
        help="the flags, which should be passed to CONCOORD and GROMACS. At \
        least the number of structures in CONCOORD and the forcefield and water \
        model should be specified in there")

#    Optional arguments
#    cliparser.add_argument('-')

    cliargs = cliparser.parse_args()

    data = DataGenerator(cliargs.wildtype, cliargs.mutations,
            cliargs.flags)
    data.fullrun()
    search = DataCollector(data)
    search.search_data()
    print(search.ener_df)
